#!/usr/bin/env bash
# CIS 5.4.2.3 - Only root group has GID zero.
# SPDX-License-Identifier: MIT
# shellcheck disable=SC2034 # Metadata is consumed by lib/module_api.sh.
RLCH_MODULE_ID="5.4.2.3"
RLCH_MODULE_TITLE="Ensure group root is the only GID 0 group"
RLCH_MODULE_DESCRIPTION="Checks /etc/group for root GID zero and other GID-zero groups."
RLCH_MODULE_RATIONALE="Prevent unintended access to root-group-owned files."
RLCH_MODULE_LEVEL="1"
RLCH_MODULE_ENABLED="true"
RLCH_MODULE_REQUIRES_REBOOT="false"
RLCH_MODULE_OPENSCAP_RULE="xccdf_org.ssgproject.content_rule_groups_no_zero_gid_except_root"
