#!/usr/bin/env bash
#
# Rocky Linux CIS Hardening Framework
#
# CIS 1.5.2 - Ensure ptrace_scope is restricted.
#
# SPDX-License-Identifier: MIT
#

RLCH_MODULE_ID="1.5.2"
RLCH_MODULE_TITLE="Ensure ptrace_scope is restricted"
RLCH_MODULE_DESCRIPTION="Ensures kernel.yama.ptrace_scope is persistently configured and active with a value of 1."
RLCH_MODULE_RATIONALE="Restricting ptrace limits the ability of processes to inspect or manipulate other processes and reduces exposure of sensitive process memory."
RLCH_MODULE_LEVEL="1"
RLCH_MODULE_ENABLED="true"
RLCH_MODULE_REQUIRES_REBOOT="false"
RLCH_MODULE_OPENSCAP_RULE="xccdf_org.ssgproject.content_rule_sysctl_kernel_yama_ptrace_scope"
