#!/usr/bin/env bash
#
# Rocky Linux CIS Hardening Framework
#
# CIS 1.1.8.3 - Ensure noexec option is set on /dev/shm partition.
#
# SPDX-License-Identifier: MIT
#

RLCH_MODULE_ID="1.1.8.3"
RLCH_MODULE_TITLE="Ensure noexec option is set on /dev/shm partition"
RLCH_MODULE_DESCRIPTION="Verifies and enforces the noexec mount option on the dedicated /dev/shm filesystem."
RLCH_MODULE_RATIONALE="The noexec option prevents binaries from being executed directly from /dev/shm and reduces the risk of unauthorized code execution."
RLCH_MODULE_LEVEL="1"
RLCH_MODULE_ENABLED="true"
RLCH_MODULE_REQUIRES_REBOOT="false"
RLCH_MODULE_OPENSCAP_RULE="xccdf_org.ssgproject.content_rule_mount_option_dev_shm_noexec"
