#!/usr/bin/env bash
#
# Rocky Linux CIS Hardening Framework
#
# CIS 1.1.8.1 - Ensure /dev/shm is a separate partition.
#
# SPDX-License-Identifier: MIT
#

RLCH_MODULE_ID="1.1.8.1"
RLCH_MODULE_TITLE="Ensure /dev/shm is a separate partition"
RLCH_MODULE_DESCRIPTION="Verifies that /dev/shm is configured as a dedicated persistent filesystem and is mounted separately at runtime."
RLCH_MODULE_RATIONALE="Configuring /dev/shm as a separate filesystem enables restrictive mount options to be applied independently to shared memory."
RLCH_MODULE_LEVEL="1"
RLCH_MODULE_ENABLED="true"
RLCH_MODULE_REQUIRES_REBOOT="false"
RLCH_MODULE_OPENSCAP_RULE="xccdf_org.ssgproject.content_rule_partition_for_dev_shm"
