#!/usr/bin/env bash
# CIS 5.3.3.2.6 - Password dictionary check.
# SPDX-License-Identifier: MIT
# shellcheck disable=SC2034 # Metadata is consumed by lib/module_api.sh.
RLCH_MODULE_ID="5.3.3.2.6"
RLCH_MODULE_TITLE="Ensure password dictionary check is configured"
RLCH_MODULE_DESCRIPTION="Requires an effective pam_pwquality dictcheck equal to one."
RLCH_MODULE_RATIONALE="Dictionary checking reduces the use of easily guessed words."
RLCH_MODULE_LEVEL="1"
RLCH_MODULE_ENABLED="true"
RLCH_MODULE_REQUIRES_REBOOT="false"
RLCH_MODULE_OPENSCAP_RULE="xccdf_org.ssgproject.content_rule_accounts_password_pam_dictcheck"
