#!/usr/bin/env bash
#
# Rocky Linux CIS Hardening Framework
#
# CIS 1.3.1 - Ensure AIDE is installed.
#
# SPDX-License-Identifier: MIT
#

RLCH_MODULE_ID="1.3.1"
RLCH_MODULE_TITLE="Ensure AIDE is installed"
RLCH_MODULE_DESCRIPTION="Ensures that the Advanced Intrusion Detection Environment (AIDE) package is installed."
RLCH_MODULE_RATIONALE="AIDE provides filesystem integrity monitoring that can detect unauthorized or unexpected changes to files and directories."
RLCH_MODULE_LEVEL="1"
RLCH_MODULE_ENABLED="true"
RLCH_MODULE_REQUIRES_REBOOT="false"
RLCH_MODULE_OPENSCAP_RULE="xccdf_org.ssgproject.content_rule_package_aide_installed"
