#!/usr/bin/env bash
#
# Rocky Linux CIS Hardening Framework
#
# CIS 1.5.1 - Ensure address space layout randomization is enabled.
#
# SPDX-License-Identifier: MIT
#

RLCH_MODULE_ID="1.5.1"
RLCH_MODULE_TITLE="Ensure address space layout randomization is enabled"
RLCH_MODULE_DESCRIPTION="Ensures kernel.randomize_va_space is persistently configured and active with a value of 2."
RLCH_MODULE_RATIONALE="Address Space Layout Randomization makes memory corruption attacks more difficult by randomizing process memory layout."
RLCH_MODULE_LEVEL="1"
RLCH_MODULE_ENABLED="true"
RLCH_MODULE_REQUIRES_REBOOT="false"
RLCH_MODULE_OPENSCAP_RULE="xccdf_org.ssgproject.content_rule_sysctl_kernel_randomize_va_space"
