#!/usr/bin/env bash
#
# Rocky Linux CIS Hardening Framework
#
# CIS 1.6.7 - Ensure system wide crypto policy disables EtM for ssh.
#
# SPDX-License-Identifier: MIT
#

RLCH_MODULE_ID="1.6.7"
RLCH_MODULE_TITLE="Ensure system wide crypto policy disables EtM for ssh"
RLCH_MODULE_DESCRIPTION="Ensures that Encrypt-then-MAC is disabled for SSH through the system-wide cryptographic policy."
RLCH_MODULE_RATIONALE="Disabling Encrypt-then-MAC for SSH mitigates exposure associated with CVE-2023-48795 when the vulnerability has not otherwise been addressed according to local site policy."
RLCH_MODULE_LEVEL="1"
RLCH_MODULE_ENABLED="true"
RLCH_MODULE_REQUIRES_REBOOT="true"
RLCH_MODULE_OPENSCAP_RULE="manual"
