#!/usr/bin/env bash
# SPDX-License-Identifier: MIT
# shellcheck disable=SC2034 # Metadata consumed by module_api.sh.
RLCH_MODULE_ID="6.2.1.4"
RLCH_MODULE_TITLE="Ensure only one logging system is in use"
RLCH_MODULE_DESCRIPTION="Observe that exactly one of rsyslog.service and systemd-journald.service is active; logging architecture requires manual selection."
RLCH_MODULE_RATIONALE="Use one logging system to avoid conflicts, resource contention and duplicate or lost logs while ensuring logging is active."
RLCH_MODULE_LEVEL="1"
RLCH_MODULE_ENABLED="true"
RLCH_MODULE_REQUIRES_REBOOT="false"
RLCH_MODULE_OPENSCAP_RULE="xccdf_org.ssgproject.content_rule_ensure_journald_and_rsyslog_not_active_together"
