#!/usr/bin/env bash
#
# Rocky Linux CIS Hardening Framework
#
# CIS 1.6.5 - Ensure system wide crypto policy disables cbc for ssh.
#
# SPDX-License-Identifier: MIT
#

RLCH_MODULE_ID="1.6.5"
RLCH_MODULE_TITLE="Ensure system wide crypto policy disables cbc for ssh"
RLCH_MODULE_DESCRIPTION="Ensures that CBC mode ciphers are disabled for SSH through the system-wide cryptographic policy."
RLCH_MODULE_RATIONALE="CBC mode ciphers have known weaknesses in SSH and should not be available when stronger authenticated or non-CBC cipher modes are supported."
RLCH_MODULE_LEVEL="1"
RLCH_MODULE_ENABLED="true"
RLCH_MODULE_REQUIRES_REBOOT="true"
RLCH_MODULE_OPENSCAP_RULE="xccdf_org.ssgproject.content_rule_configure_custom_crypto_policy_cis"
