#!/usr/bin/env bash
#
# Rocky Linux CIS Hardening Framework
# CIS 1.8.6 - Ensure GDM automatic mounting of removable media is disabled.
# SPDX-License-Identifier: MIT
#
RLCH_MODULE_ID="1.8.6"
RLCH_MODULE_TITLE="Ensure GDM automatic mounting of removable media is disabled"
RLCH_MODULE_DESCRIPTION="Ensures GNOME does not automatically mount or automatically open removable media when GDM is installed."
RLCH_MODULE_RATIONALE="Disabling automatic mounting and opening of removable media reduces the risk of untrusted media being accessed without explicit user action."
RLCH_MODULE_LEVEL="1"
RLCH_MODULE_ENABLED="true"
RLCH_MODULE_REQUIRES_REBOOT="false"
RLCH_MODULE_OPENSCAP_RULE="xccdf_org.ssgproject.content_rule_dconf_gnome_disable_automount"
