#!/usr/bin/env bash
#
# Rocky Linux CIS Hardening Framework
#
# CIS 1.2.1 - Ensure GPG keys are configured.
#
# SPDX-License-Identifier: MIT
#

RLCH_MODULE_ID="1.2.1"
RLCH_MODULE_TITLE="Ensure GPG keys are configured"
RLCH_MODULE_DESCRIPTION="Verifies that at least one RPM GPG public key is installed. Because this CIS recommendation requires manual verification of trusted repository signing keys, the framework does not automatically import keys."
RLCH_MODULE_RATIONALE="Package signing keys are used to validate the authenticity and integrity of software packages obtained from configured repositories."
RLCH_MODULE_LEVEL="1"
RLCH_MODULE_ENABLED="true"
RLCH_MODULE_REQUIRES_REBOOT="false"
RLCH_MODULE_OPENSCAP_RULE=""
