#!/usr/bin/env bash
#
# Rocky Linux CIS Hardening Framework
#
# CIS 2.1.15 - Ensure telnet server services are not in use.
#
# SPDX-License-Identifier: MIT
#

RLCH_MODULE_ID="2.1.15"
RLCH_MODULE_TITLE="Ensure telnet server services are not in use"
RLCH_MODULE_DESCRIPTION="Ensures the telnet-server package is not installed so that insecure Telnet server services cannot be used."
RLCH_MODULE_RATIONALE="Telnet transmits authentication credentials and session data without encryption. Removing the Telnet server reduces the attack surface and prevents use of this insecure remote access protocol."
RLCH_MODULE_LEVEL="1"
RLCH_MODULE_ENABLED="true"
RLCH_MODULE_REQUIRES_REBOOT="false"
RLCH_MODULE_OPENSCAP_RULE="xccdf_org.ssgproject.content_rule_package_telnet-server_removed"
