#!/usr/bin/env bash
#
# Rocky Linux CIS Hardening Framework
#
# CIS 1.1.1.7 - Ensure udf kernel module is not available.
#
# SPDX-License-Identifier: MIT
#
RLCH_MODULE_ID="1.1.1.7"
RLCH_MODULE_TITLE="Ensure udf kernel module is not available"
RLCH_MODULE_DESCRIPTION="Disables the udf kernel module by configuring modprobe to prevent the module from being loaded."
RLCH_MODULE_RATIONALE="Removing support for unused kernel modules reduces the local kernel attack surface."
RLCH_MODULE_LEVEL="1"
RLCH_MODULE_ENABLED="true"
RLCH_MODULE_REQUIRES_REBOOT="false"
RLCH_MODULE_OPENSCAP_RULE="xccdf_org.ssgproject.content_rule_kernel_module_udf_disabled"
