#!/usr/bin/env bash
#
# Rocky Linux CIS Hardening Framework
#
# CIS 1.1.2.1 - Ensure /tmp is a separate partition.
#
# SPDX-License-Identifier: MIT
#

RLCH_MODULE_ID="1.1.2.1"
RLCH_MODULE_TITLE="Ensure /tmp is a separate partition"
RLCH_MODULE_DESCRIPTION="Verifies that /tmp is configured as a dedicated persistent filesystem and is mounted separately at runtime."
RLCH_MODULE_RATIONALE="Using a separate filesystem for /tmp limits the impact of uncontrolled temporary file growth and allows dedicated mount restrictions to be applied."
RLCH_MODULE_LEVEL="1"
RLCH_MODULE_ENABLED="true"
RLCH_MODULE_REQUIRES_REBOOT="false"
RLCH_MODULE_OPENSCAP_RULE="xccdf_org.ssgproject.content_rule_partition_for_tmp"