#!/usr/bin/env bash
#
# Rocky Linux CIS Hardening Framework
#
# CIS 1.8.4 - Ensure GDM screen locks when the user is idle.
#
# SPDX-License-Identifier: MIT
#

RLCH_MODULE_ID="1.8.4"
RLCH_MODULE_TITLE="Ensure GDM screen locks when the user is idle"
RLCH_MODULE_DESCRIPTION="Ensures GNOME sessions activate the screensaver after no more than 15 minutes of inactivity and lock the screen within 5 seconds."
RLCH_MODULE_RATIONALE="Automatically locking inactive graphical sessions reduces the risk of unauthorized access to unattended sessions."
RLCH_MODULE_LEVEL="1"
RLCH_MODULE_ENABLED="true"
RLCH_MODULE_REQUIRES_REBOOT="false"
RLCH_MODULE_OPENSCAP_RULE="xccdf_org.ssgproject.content_rule_dconf_gnome_screensaver_idle_delay"
