#!/usr/bin/env bash
#
# Rocky Linux CIS Hardening Framework
#
# CIS 1.2.2 - Ensure gpgcheck is globally activated.
#
# SPDX-License-Identifier: MIT
#

RLCH_MODULE_ID="1.2.2"
RLCH_MODULE_TITLE="Ensure gpgcheck is globally activated"
RLCH_MODULE_DESCRIPTION="Ensures that DNF globally verifies package signatures by configuring gpgcheck=1 in the [main] section of /etc/dnf/dnf.conf."
RLCH_MODULE_RATIONALE="Enabling global package signature verification helps ensure that installed software originates from trusted sources and has not been modified."
RLCH_MODULE_LEVEL="1"
RLCH_MODULE_ENABLED="true"
RLCH_MODULE_REQUIRES_REBOOT="false"
RLCH_MODULE_OPENSCAP_RULE="xccdf_org.ssgproject.content_rule_ensure_gpgcheck_globally_activated"
