#!/usr/bin/env bash
#
# Rocky Linux CIS Hardening Framework
#
# CIS 1.7.4 - Ensure access to /etc/motd is configured.
#
# SPDX-License-Identifier: MIT
#

RLCH_MODULE_ID="1.7.4"
RLCH_MODULE_TITLE="Ensure access to /etc/motd is configured"
RLCH_MODULE_DESCRIPTION="Ensures /etc/motd is owned by root:root and does not grant write or execute permissions to group or other users."
RLCH_MODULE_RATIONALE="Restricting ownership and permissions on /etc/motd prevents unauthorized users from modifying the system message displayed after login."
RLCH_MODULE_LEVEL="1"
RLCH_MODULE_ENABLED="true"
RLCH_MODULE_REQUIRES_REBOOT="false"
RLCH_MODULE_OPENSCAP_RULE="xccdf_org.ssgproject.content_rule_file_groupowner_etc_motd"
