#!/usr/bin/env bash
#
# Rocky Linux CIS Hardening Framework
#
# Framework configuration
#
# SPDX-License-Identifier: MIT
#

# Require root privileges for commands that modify the system.
RLCH_REQUIRE_ROOT="true"

# Stop execution when an optional configuration file cannot be loaded.
RLCH_STRICT_CONFIGURATION="true"

# Default command executed when no command is provided.
RLCH_DEFAULT_COMMAND="help"

# Default OpenSCAP profile.
RLCH_OPENSCAP_PROFILE="xccdf_org.ssgproject.content_profile_cis_server_l1"