#!/usr/bin/env bash
#
# Rocky Linux CIS Hardening Framework
#
# Logging configuration
#
# SPDX-License-Identifier: MIT
#

RLCH_LOG_LEVEL="INFO"
RLCH_LOG_TO_CONSOLE="true"
RLCH_LOG_TO_FILE="true"
RLCH_LOG_FILENAME="framework.log"
RLCH_LOG_DATE_FORMAT="%Y-%m-%d %H:%M:%S"