#!/usr/bin/env bash
#
# Rocky Linux CIS Hardening Framework
#
# CIS 1.6.1 - Ensure system wide crypto policy is not set to legacy.
#
# SPDX-License-Identifier: MIT
#

RLCH_MODULE_ID="1.6.1"
RLCH_MODULE_TITLE="Ensure system wide crypto policy is not set to legacy"
RLCH_MODULE_DESCRIPTION="Ensures that the system-wide cryptographic policy does not use the LEGACY base policy."
RLCH_MODULE_RATIONALE="The LEGACY cryptographic policy permits algorithms and protocol settings that are unsuitable for a hardened system."
RLCH_MODULE_LEVEL="1"
RLCH_MODULE_ENABLED="true"
RLCH_MODULE_REQUIRES_REBOOT="false"
RLCH_MODULE_OPENSCAP_RULE="xccdf_org.ssgproject.content_rule_configure_custom_crypto_policy_cis"
