#!/usr/bin/env bash
# Rocky Linux CIS Hardening Framework
# CIS 2.1.18 - Ensure web server services are not in use.
# SPDX-License-Identifier: MIT
RLCH_MODULE_ID="2.1.18"
RLCH_MODULE_TITLE="Ensure web server services are not in use"
RLCH_MODULE_DESCRIPTION="Ensures the Apache HTTP Server and nginx web server packages are not installed."
RLCH_MODULE_RATIONALE="Unnecessary web server software increases the attack surface. Removing Apache HTTP Server and nginx prevents unused web services from being exposed or misconfigured."
RLCH_MODULE_LEVEL="1"
RLCH_MODULE_ENABLED="true"
RLCH_MODULE_REQUIRES_REBOOT="false"
RLCH_MODULE_OPENSCAP_RULE="xccdf_org.ssgproject.content_rule_package_httpd_removed"
