#!/usr/bin/env bash
#
# Rocky Linux CIS Hardening Framework
#
# CIS 1.1.7.1 - Ensure separate partition exists for /home.
#
# SPDX-License-Identifier: MIT
#

RLCH_MODULE_ID="1.1.7.1"
RLCH_MODULE_TITLE="Ensure separate partition exists for /home"
RLCH_MODULE_DESCRIPTION="Verifies that /home is configured as a dedicated persistent filesystem and is mounted separately at runtime."
RLCH_MODULE_RATIONALE="Using a separate filesystem for /home provides additional isolation for user data and helps prevent user-controlled files from consuming space required by system filesystems."
RLCH_MODULE_LEVEL="1"
RLCH_MODULE_ENABLED="true"
RLCH_MODULE_REQUIRES_REBOOT="false"
RLCH_MODULE_OPENSCAP_RULE="xccdf_org.ssgproject.content_rule_partition_for_home"
