#!/usr/bin/env bash
#
# Rocky Linux CIS Hardening Framework
#
# CIS 1.3.2 - Ensure filesystem integrity is regularly checked.
#
# SPDX-License-Identifier: MIT
#

RLCH_MODULE_ID="1.3.2"
RLCH_MODULE_TITLE="Ensure filesystem integrity is regularly checked"
RLCH_MODULE_DESCRIPTION="Ensures that AIDE is scheduled to perform a filesystem integrity check at least weekly."
RLCH_MODULE_RATIONALE="Periodic AIDE checks help identify unexpected or unauthorized filesystem changes by comparing the current system state with the established integrity database."
RLCH_MODULE_LEVEL="1"
RLCH_MODULE_ENABLED="true"
RLCH_MODULE_REQUIRES_REBOOT="false"
RLCH_MODULE_OPENSCAP_RULE="xccdf_org.ssgproject.content_rule_aide_periodic_cron_checking"
