#!/usr/bin/env bash
# CIS 5.2.2 - Ensure sudo commands use pty.
# SPDX-License-Identifier: MIT
# shellcheck disable=SC2034 # Metadata is consumed by lib/module_api.sh.
RLCH_MODULE_ID="5.2.2"
RLCH_MODULE_TITLE="Ensure sudo commands use pty"
RLCH_MODULE_DESCRIPTION="Ensures sudo runs commands in a pseudo-terminal."
RLCH_MODULE_RATIONALE="A pseudo-terminal prevents a background process from retaining a user's terminal after sudo exits."
RLCH_MODULE_LEVEL="1"
RLCH_MODULE_ENABLED="true"
RLCH_MODULE_REQUIRES_REBOOT="false"
RLCH_MODULE_OPENSCAP_RULE="xccdf_org.ssgproject.content_rule_sudo_add_use_pty"
