#!/usr/bin/env bash
#
# Rocky Linux CIS Hardening Framework
#
# CIS 2.1.3 - Ensure dhcp server services are not in use.
#
# SPDX-License-Identifier: MIT
#

RLCH_MODULE_ID="2.1.3"
RLCH_MODULE_TITLE="Ensure dhcp server services are not in use"
RLCH_MODULE_DESCRIPTION="Ensures the DHCP server package is not installed."
RLCH_MODULE_RATIONALE="Removing the DHCP server package prevents the system from providing DHCP services unless explicitly required."
RLCH_MODULE_LEVEL="1"
RLCH_MODULE_ENABLED="true"
RLCH_MODULE_REQUIRES_REBOOT="false"
RLCH_MODULE_OPENSCAP_RULE="xccdf_org.ssgproject.content_rule_package_dhcp_removed"
