#!/usr/bin/env bash
#
# Rocky Linux CIS Hardening Framework
#
# CIS 2.1.1 - Ensure autofs services are not in use.
#
# SPDX-License-Identifier: MIT
#

RLCH_MODULE_ID="2.1.1"
RLCH_MODULE_TITLE="Ensure autofs services are not in use"
RLCH_MODULE_DESCRIPTION="Ensures the autofs service is stopped, disabled, and masked when autofs is installed."
RLCH_MODULE_RATIONALE="Disabling autofs reduces the risk associated with automatic mounting of local or remote filesystems that are not explicitly required."
RLCH_MODULE_LEVEL="1"
RLCH_MODULE_ENABLED="true"
RLCH_MODULE_REQUIRES_REBOOT="false"
RLCH_MODULE_OPENSCAP_RULE="xccdf_org.ssgproject.content_rule_service_autofs_disabled"
