#!/usr/bin/env bash
#
# Rocky Linux CIS Hardening Framework
#
# CIS 1.6.4 - Ensure system wide crypto policy disables macs less than 128 bits.
#
# SPDX-License-Identifier: MIT
#

RLCH_MODULE_ID="1.6.4"
RLCH_MODULE_TITLE="Ensure system wide crypto policy disables macs less than 128 bits"
RLCH_MODULE_DESCRIPTION="Ensures that system-wide cryptographic policy disables Message Authentication Codes with security strength below 128 bits."
RLCH_MODULE_RATIONALE="Weak Message Authentication Codes reduce integrity protection and can expose protected communications to cryptographic attacks."
RLCH_MODULE_LEVEL="1"
RLCH_MODULE_ENABLED="true"
RLCH_MODULE_REQUIRES_REBOOT="true"
RLCH_MODULE_OPENSCAP_RULE="xccdf_org.ssgproject.content_rule_configure_custom_crypto_policy_cis"
