#!/usr/bin/env bash
#
# Rocky Linux CIS Hardening Framework
#
# CIS 1.1.1.4 - Ensure hfsplus kernel module is not available.
#
# SPDX-License-Identifier: MIT
#
RLCH_MODULE_ID="1.1.1.4"
RLCH_MODULE_TITLE="Ensure hfsplus kernel module is not available"
RLCH_MODULE_DESCRIPTION="Disables the hfsplus kernel module by configuring modprobe to prevent the module from being loaded."
RLCH_MODULE_RATIONALE="Removing support for unused filesystem types reduces the local kernel attack surface."
RLCH_MODULE_LEVEL="1"
RLCH_MODULE_ENABLED="true"
RLCH_MODULE_REQUIRES_REBOOT="false"
RLCH_MODULE_OPENSCAP_RULE="xccdf_org.ssgproject.content_rule_kernel_module_hfsplus_disabled"
