#!/usr/bin/env bash
#
# Rocky Linux CIS Hardening Framework
#
# CIS 2.1.7 - Ensure ftp server services are not in use.
#
# SPDX-License-Identifier: MIT
#

RLCH_MODULE_ID="2.1.7"
RLCH_MODULE_TITLE="Ensure ftp server services are not in use"
RLCH_MODULE_DESCRIPTION="Ensures the vsftpd FTP server package is not installed."
RLCH_MODULE_RATIONALE="Removing the FTP server package prevents the system from providing unencrypted FTP services unless explicitly required."
RLCH_MODULE_LEVEL="1"
RLCH_MODULE_ENABLED="true"
RLCH_MODULE_REQUIRES_REBOOT="false"
RLCH_MODULE_OPENSCAP_RULE="xccdf_org.ssgproject.content_rule_package_vsftpd_removed"
